#!/usr/bin/env swift
// The canonical, deterministic vector definition of the Forma app icon.
// Run from any directory: swift /path/to/forma/scripts/generate-icon.swift [output-directory]
// Only small raster sizes receive optical stroke adjustment. The SVG is the vector master.
import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers

struct IconError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}

let fileManager = FileManager.default
let source = URL(fileURLWithPath: CommandLine.arguments[0]).standardizedFileURL
let output = CommandLine.arguments.count == 2
    ? URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true).standardizedFileURL
    : source.deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent("assets", isDirectory: true)

// These restrained colors and the three-edge cube extend the editor's native mark.
let tile = "1B1E21"
let tileEdge = "39413F"
let mint = "8BC7B6"
let topFill = "2C4740"
let leftFill = "22342F"
let rightFill = "273D35"
let top = CGPoint(x: 512, y: 236)
let upperRight = CGPoint(x: 744, y: 370)
let lowerRight = CGPoint(x: 744, y: 638)
let bottom = CGPoint(x: 512, y: 772)
let lowerLeft = CGPoint(x: 280, y: 638)
let upperLeft = CGPoint(x: 280, y: 370)
let center = CGPoint(x: 512, y: 504)
let faces: [([CGPoint], String)] = [
    ([top, upperRight, center, upperLeft], topFill),
    ([upperLeft, center, bottom, lowerLeft], leftFill),
    ([center, upperRight, lowerRight, bottom], rightFill),
]
let silhouette = [top, upperRight, lowerRight, bottom, lowerLeft, upperLeft]
let insideEdges = [[upperLeft, center, upperRight], [center, bottom]]

func color(_ hex: String) -> CGColor {
    let bits = UInt32(hex, radix: 16)!
    return CGColor(srgbRed: CGFloat((bits >> 16) & 255) / 255,
                   green: CGFloat((bits >> 8) & 255) / 255,
                   blue: CGFloat(bits & 255) / 255, alpha: 1)
}

func path(_ points: [CGPoint], closed: Bool = false) -> CGPath {
    let path = CGMutablePath()
    path.move(to: points[0])
    for point in points.dropFirst() { path.addLine(to: point) }
    if closed { path.closeSubpath() }
    return path
}

func svgPath(_ points: [CGPoint], closed: Bool = false) -> String {
    points.enumerated().map { index, p in
        "\(index == 0 ? "M" : "L")\(Int(p.x)) \(Int(p.y))"
    }.joined(separator: " ") + (closed ? " Z" : "")
}

func vectorMaster() -> String {
    let facePaths = faces.map { points, fill in
        "    <path d=\"\(svgPath(points, closed: true))\" fill=\"#\(fill)\"/>"
    }.joined(separator: "\n")
    let edges = insideEdges.map { points in
        "    <path d=\"\(svgPath(points))\"/>"
    }.joined(separator: "\n")
    return """
    <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-labelledby="title description">
      <title id="title">Forma</title>
      <desc id="description">A mint geometric cube on a rounded charcoal tile.</desc>
      <!-- Generated by scripts/generate-icon.swift; the script is the canonical source. -->
      <rect x="64" y="64" width="896" height="896" rx="200" fill="#\(tile)" stroke="#\(tileEdge)" stroke-width="2"/>
    \(facePaths)
      <g fill="none" stroke="#\(mint)" stroke-width="24" stroke-linejoin="round" stroke-linecap="round">
        <path d="\(svgPath(silhouette, closed: true))"/>
    \(edges)
      </g>
    </svg>

    """
}

func render(size: Int) throws -> CGImage {
    guard let context = CGContext(data: nil, width: size, height: size,
        bitsPerComponent: 8, bytesPerRow: size * 4,
        space: CGColorSpace(name: CGColorSpace.sRGB)!,
        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
    else { throw IconError("Could not allocate the \(size) px icon canvas") }
    let scale = CGFloat(size) / 1024
    context.translateBy(x: 0, y: CGFloat(size))
    context.scaleBy(x: scale, y: -scale)
    context.setShouldAntialias(true)
    context.setAllowsAntialiasing(true)
    let tilePath = CGPath(roundedRect: CGRect(x: 64, y: 64, width: 896, height: 896),
                          cornerWidth: 200, cornerHeight: 200, transform: nil)
    context.addPath(tilePath)
    context.setFillColor(color(tile))
    context.fillPath()
    // The tile's fine edge helps its outline remain visible on dark desktops.
    context.addPath(tilePath)
    context.setStrokeColor(color(tileEdge))
    context.setLineWidth(max(2, 0.4 / scale))
    context.strokePath()
    for (points, fill) in faces {
        context.addPath(path(points, closed: true))
        context.setFillColor(color(fill))
        context.fillPath()
    }
    context.setStrokeColor(color(mint))
    context.setLineWidth(max(24, 0.9 / scale))
    context.setLineJoin(.round)
    context.setLineCap(.round)
    context.addPath(path(silhouette, closed: true))
    context.strokePath()
    for points in insideEdges {
        context.addPath(path(points))
        context.strokePath()
    }
    guard let image = context.makeImage() else { throw IconError("Could not finalize icon image") }
    return image
}

func writePNG(_ image: CGImage, to url: URL) throws {
    guard let destination = CGImageDestinationCreateWithURL(url as CFURL, UTType.png.identifier as CFString, 1, nil)
    else { throw IconError("Could not create \(url.path)") }
    CGImageDestinationAddImage(destination, image, nil)
    guard CGImageDestinationFinalize(destination) else { throw IconError("Could not encode \(url.path)") }
}

func generate() throws {
    guard CommandLine.arguments.count <= 2 else { throw IconError("Usage: generate-icon.swift [output-directory]") }
    try fileManager.createDirectory(at: output, withIntermediateDirectories: true)
    let temporary = fileManager.temporaryDirectory.appendingPathComponent("forma-icon-\(UUID().uuidString)", isDirectory: true)
    let iconset = temporary.appendingPathComponent("Forma.iconset", isDirectory: true)
    try fileManager.createDirectory(at: iconset, withIntermediateDirectories: true)
    defer { try? fileManager.removeItem(at: temporary) }
    let sizes: [(String, Int)] = [
        ("icon_16x16.png", 16), ("icon_16x16@2x.png", 32),
        ("icon_32x32.png", 32), ("icon_32x32@2x.png", 64),
        ("icon_128x128.png", 128), ("icon_128x128@2x.png", 256),
        ("icon_256x256.png", 256), ("icon_256x256@2x.png", 512),
        ("icon_512x512.png", 512), ("icon_512x512@2x.png", 1024),
    ]
    var renders: [Int: CGImage] = [:]
    for (name, size) in sizes {
        let image: CGImage
        if let cached = renders[size] { image = cached }
        else { image = try render(size: size); renders[size] = image }
        try writePNG(image, to: iconset.appendingPathComponent(name))
    }
    let icns = temporary.appendingPathComponent("Forma.icns")
    let iconutil = Process()
    iconutil.executableURL = URL(fileURLWithPath: "/usr/bin/iconutil")
    iconutil.arguments = ["--convert", "icns", "--output", icns.path, iconset.path]
    try iconutil.run()
    iconutil.waitUntilExit()
    guard iconutil.terminationStatus == 0 else { throw IconError("iconutil exited with \(iconutil.terminationStatus)") }
    try Data(contentsOf: icns).write(to: output.appendingPathComponent("Forma.icns"), options: .atomic)
    try Data(contentsOf: iconset.appendingPathComponent("icon_512x512@2x.png"))
        .write(to: output.appendingPathComponent("Forma.png"), options: .atomic)
    try vectorMaster().write(to: output.appendingPathComponent("Forma.svg"), atomically: true, encoding: .utf8)
    // A small native-size reference makes optical adjustments straightforward to inspect.
    try Data(contentsOf: iconset.appendingPathComponent("icon_32x32@2x.png"))
        .write(to: output.appendingPathComponent("Forma-64.png"), options: .atomic)
    print("Generated Forma.svg, Forma.png, Forma-64.png and Forma.icns in \(output.path)")
}

do { try generate() }
catch { fputs("Forma icon: \(error)\n", stderr); exit(1) }
